//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 04.02.2010 11:36:39
using System;
using System.Data.Services.Client;
using System.Data.Services.Common;

namespace ASPNET.StarterKit.Portal.PortalContextServiceReference
{
    /// <summary>
    /// There are no comments for PortalContext in the schema.
    /// </summary>
    public partial class PortalContext : DataServiceContext
    {
        private DataServiceQuery<PortalAnnouncement> _Announcements;
        private DataServiceQuery<PortalContact> _Contacts;
        private DataServiceQuery<PortalEvent> _Events;
        private DataServiceQuery<PortalLink> _Links;

        /// <summary>
        /// Initialize a new PortalContext object.
        /// </summary>
        public PortalContext(Uri serviceRoot) :
            base(serviceRoot)
        {
            ResolveName = new Func<Type, string>(ResolveNameFromType);
            ResolveType = new Func<string, Type>(ResolveTypeFromName);
            OnContextCreated();
        }

        /// <summary>
        /// There are no comments for Announcements in the schema.
        /// </summary>
        public DataServiceQuery<PortalAnnouncement> Announcements
        {
            get
            {
                if ((_Announcements == null))
                {
                    _Announcements = base.CreateQuery<PortalAnnouncement>("Announcements");
                }
                return _Announcements;
            }
        }

        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        public DataServiceQuery<PortalContact> Contacts
        {
            get
            {
                if ((_Contacts == null))
                {
                    _Contacts = base.CreateQuery<PortalContact>("Contacts");
                }
                return _Contacts;
            }
        }

        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        public DataServiceQuery<PortalEvent> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateQuery<PortalEvent>("Events");
                }
                return _Events;
            }
        }

        /// <summary>
        /// There are no comments for Links in the schema.
        /// </summary>
        public new DataServiceQuery<PortalLink> Links
        {
            get
            {
                if ((_Links == null))
                {
                    _Links = base.CreateQuery<PortalLink>("Links");
                }
                return _Links;
            }
        }

        partial void OnContextCreated();

        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        protected Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ASPNET.StarterKit.Portal", StringComparison.Ordinal))
            {
                return GetType().Assembly.GetType(string.Concat("ASPNET.StarterKit.Portal.PortalContextServiceReference", typeName.Substring(24)), true);
            }
            return null;
        }

        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        protected string ResolveNameFromType(Type clientType)
        {
            if (clientType.Namespace.Equals("ASPNET.StarterKit.Portal.PortalContextServiceReference", StringComparison.Ordinal))
            {
                return string.Concat("ASPNET.StarterKit.Portal.", clientType.Name);
            }
            return null;
        }

        /// <summary>
        /// There are no comments for Announcements in the schema.
        /// </summary>
        public void AddToAnnouncements(PortalAnnouncement portalAnnouncement)
        {
            base.AddObject("Announcements", portalAnnouncement);
        }

        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        public void AddToContacts(PortalContact portalContact)
        {
            base.AddObject("Contacts", portalContact);
        }

        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        public void AddToEvents(PortalEvent portalEvent)
        {
            base.AddObject("Events", portalEvent);
        }

        /// <summary>
        /// There are no comments for Links in the schema.
        /// </summary>
        public void AddToLinks(PortalLink portalLink)
        {
            base.AddObject("Links", portalLink);
        }
    }

    /// <summary>
    /// There are no comments for ASPNET.StarterKit.Portal.PortalAnnouncement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemId
    /// </KeyProperties>
    [DataServiceKey("ItemId")]
    public partial class PortalAnnouncement
    {
        private string _CreatedByUser;
        private Nullable<DateTime> _CreatedDate;
        private string _Description;
        private Nullable<DateTime> _ExpireDate;
        private int _ItemId;
        private string _MobileMoreLink;
        private int _ModuleId;
        private string _MoreLink;
        private string _Title;

        /// <summary>
        /// There are no comments for Property ModuleId in the schema.
        /// </summary>
        public int ModuleId
        {
            get { return _ModuleId; }
            set
            {
                OnModuleIdChanging(value);
                _ModuleId = value;
                OnModuleIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        public int ItemId
        {
            get { return _ItemId; }
            set
            {
                OnItemIdChanging(value);
                _ItemId = value;
                OnItemIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedByUser in the schema.
        /// </summary>
        public string CreatedByUser
        {
            get { return _CreatedByUser; }
            set
            {
                OnCreatedByUserChanging(value);
                _CreatedByUser = value;
                OnCreatedByUserChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ExpireDate in the schema.
        /// </summary>
        public Nullable<DateTime> ExpireDate
        {
            get { return _ExpireDate; }
            set
            {
                OnExpireDateChanging(value);
                _ExpireDate = value;
                OnExpireDateChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        public Nullable<DateTime> CreatedDate
        {
            get { return _CreatedDate; }
            set
            {
                OnCreatedDateChanging(value);
                _CreatedDate = value;
                OnCreatedDateChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        public string Title
        {
            get { return _Title; }
            set
            {
                OnTitleChanging(value);
                _Title = value;
                OnTitleChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        public string Description
        {
            get { return _Description; }
            set
            {
                OnDescriptionChanging(value);
                _Description = value;
                OnDescriptionChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property MoreLink in the schema.
        /// </summary>
        public string MoreLink
        {
            get { return _MoreLink; }
            set
            {
                OnMoreLinkChanging(value);
                _MoreLink = value;
                OnMoreLinkChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property MobileMoreLink in the schema.
        /// </summary>
        public string MobileMoreLink
        {
            get { return _MobileMoreLink; }
            set
            {
                OnMobileMoreLinkChanging(value);
                _MobileMoreLink = value;
                OnMobileMoreLinkChanged();
            }
        }

        /// <summary>
        /// Create a new PortalAnnouncement object.
        /// </summary>
        /// <param name="moduleId">Initial value of ModuleId.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        public static PortalAnnouncement CreatePortalAnnouncement(int moduleId, int itemId)
        {
            var portalAnnouncement = new PortalAnnouncement();
            portalAnnouncement.ModuleId = moduleId;
            portalAnnouncement.ItemId = itemId;
            return portalAnnouncement;
        }

        partial void OnModuleIdChanging(int value);
        partial void OnModuleIdChanged();

        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();

        partial void OnCreatedByUserChanging(string value);
        partial void OnCreatedByUserChanged();

        partial void OnExpireDateChanging(Nullable<DateTime> value);
        partial void OnExpireDateChanged();

        partial void OnCreatedDateChanging(Nullable<DateTime> value);
        partial void OnCreatedDateChanged();

        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();

        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();

        partial void OnMoreLinkChanging(string value);
        partial void OnMoreLinkChanged();

        partial void OnMobileMoreLinkChanging(string value);
        partial void OnMobileMoreLinkChanged();
    }

    /// <summary>
    /// There are no comments for ASPNET.StarterKit.Portal.PortalContact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemId
    /// </KeyProperties>
    [DataServiceKey("ItemId")]
    public partial class PortalContact
    {
        private string _Contact1;
        private string _Contact2;
        private string _CreatedByUser;
        private Nullable<DateTime> _CreatedDate;
        private string _Email;
        private int _ItemId;
        private int _ModuleId;
        private string _Name;
        private string _Role;

        /// <summary>
        /// There are no comments for Property ModuleId in the schema.
        /// </summary>
        public int ModuleId
        {
            get { return _ModuleId; }
            set
            {
                OnModuleIdChanging(value);
                _ModuleId = value;
                OnModuleIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        public int ItemId
        {
            get { return _ItemId; }
            set
            {
                OnItemIdChanging(value);
                _ItemId = value;
                OnItemIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedByUser in the schema.
        /// </summary>
        public string CreatedByUser
        {
            get { return _CreatedByUser; }
            set
            {
                OnCreatedByUserChanging(value);
                _CreatedByUser = value;
                OnCreatedByUserChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        public Nullable<DateTime> CreatedDate
        {
            get { return _CreatedDate; }
            set
            {
                OnCreatedDateChanging(value);
                _CreatedDate = value;
                OnCreatedDateChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                OnNameChanging(value);
                _Name = value;
                OnNameChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Role in the schema.
        /// </summary>
        public string Role
        {
            get { return _Role; }
            set
            {
                OnRoleChanging(value);
                _Role = value;
                OnRoleChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        public string Email
        {
            get { return _Email; }
            set
            {
                OnEmailChanging(value);
                _Email = value;
                OnEmailChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Contact1 in the schema.
        /// </summary>
        public string Contact1
        {
            get { return _Contact1; }
            set
            {
                OnContact1Changing(value);
                _Contact1 = value;
                OnContact1Changed();
            }
        }

        /// <summary>
        /// There are no comments for Property Contact2 in the schema.
        /// </summary>
        public string Contact2
        {
            get { return _Contact2; }
            set
            {
                OnContact2Changing(value);
                _Contact2 = value;
                OnContact2Changed();
            }
        }

        /// <summary>
        /// Create a new PortalContact object.
        /// </summary>
        /// <param name="moduleId">Initial value of ModuleId.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        public static PortalContact CreatePortalContact(int moduleId, int itemId)
        {
            var portalContact = new PortalContact();
            portalContact.ModuleId = moduleId;
            portalContact.ItemId = itemId;
            return portalContact;
        }

        partial void OnModuleIdChanging(int value);
        partial void OnModuleIdChanged();

        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();

        partial void OnCreatedByUserChanging(string value);
        partial void OnCreatedByUserChanged();

        partial void OnCreatedDateChanging(Nullable<DateTime> value);
        partial void OnCreatedDateChanged();

        partial void OnNameChanging(string value);
        partial void OnNameChanged();

        partial void OnRoleChanging(string value);
        partial void OnRoleChanged();

        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();

        partial void OnContact1Changing(string value);
        partial void OnContact1Changed();

        partial void OnContact2Changing(string value);
        partial void OnContact2Changed();
    }

    /// <summary>
    /// There are no comments for ASPNET.StarterKit.Portal.PortalEvent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemId
    /// </KeyProperties>
    [DataServiceKey("ItemId")]
    public partial class PortalEvent
    {
        private string _CreatedByUser;
        private Nullable<DateTime> _CreatedDate;
        private string _Description;
        private DateTime _ExpireDate;
        private int _ItemId;
        private int _ModuleId;
        private string _Title;
        private string _WhereWhen;

        /// <summary>
        /// There are no comments for Property ModuleId in the schema.
        /// </summary>
        public int ModuleId
        {
            get { return _ModuleId; }
            set
            {
                OnModuleIdChanging(value);
                _ModuleId = value;
                OnModuleIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        public int ItemId
        {
            get { return _ItemId; }
            set
            {
                OnItemIdChanging(value);
                _ItemId = value;
                OnItemIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedByUser in the schema.
        /// </summary>
        public string CreatedByUser
        {
            get { return _CreatedByUser; }
            set
            {
                OnCreatedByUserChanging(value);
                _CreatedByUser = value;
                OnCreatedByUserChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        public Nullable<DateTime> CreatedDate
        {
            get { return _CreatedDate; }
            set
            {
                OnCreatedDateChanging(value);
                _CreatedDate = value;
                OnCreatedDateChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ExpireDate in the schema.
        /// </summary>
        public DateTime ExpireDate
        {
            get { return _ExpireDate; }
            set
            {
                OnExpireDateChanging(value);
                _ExpireDate = value;
                OnExpireDateChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        public string Title
        {
            get { return _Title; }
            set
            {
                OnTitleChanging(value);
                _Title = value;
                OnTitleChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        public string Description
        {
            get { return _Description; }
            set
            {
                OnDescriptionChanging(value);
                _Description = value;
                OnDescriptionChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property WhereWhen in the schema.
        /// </summary>
        public string WhereWhen
        {
            get { return _WhereWhen; }
            set
            {
                OnWhereWhenChanging(value);
                _WhereWhen = value;
                OnWhereWhenChanged();
            }
        }

        /// <summary>
        /// Create a new PortalEvent object.
        /// </summary>
        /// <param name="moduleId">Initial value of ModuleId.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="expireDate">Initial value of ExpireDate.</param>
        public static PortalEvent CreatePortalEvent(int moduleId, int itemId, DateTime expireDate)
        {
            var portalEvent = new PortalEvent();
            portalEvent.ModuleId = moduleId;
            portalEvent.ItemId = itemId;
            portalEvent.ExpireDate = expireDate;
            return portalEvent;
        }

        partial void OnModuleIdChanging(int value);
        partial void OnModuleIdChanged();

        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();

        partial void OnCreatedByUserChanging(string value);
        partial void OnCreatedByUserChanged();

        partial void OnCreatedDateChanging(Nullable<DateTime> value);
        partial void OnCreatedDateChanged();

        partial void OnExpireDateChanging(DateTime value);
        partial void OnExpireDateChanged();

        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();

        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();

        partial void OnWhereWhenChanging(string value);
        partial void OnWhereWhenChanged();
    }

    /// <summary>
    /// There are no comments for ASPNET.StarterKit.Portal.PortalLink in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemId
    /// </KeyProperties>
    [DataServiceKey("ItemId")]
    public partial class PortalLink
    {
        private string _CreatedByUser;
        private Nullable<DateTime> _CreatedDate;
        private string _Description;
        private int _ItemId;
        private string _MobileUrl;
        private int _ModuleId;
        private string _Title;
        private string _Url;
        private Nullable<int> _ViewOrder;

        /// <summary>
        /// There are no comments for Property ModuleId in the schema.
        /// </summary>
        public int ModuleId
        {
            get { return _ModuleId; }
            set
            {
                OnModuleIdChanging(value);
                _ModuleId = value;
                OnModuleIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        public int ItemId
        {
            get { return _ItemId; }
            set
            {
                OnItemIdChanging(value);
                _ItemId = value;
                OnItemIdChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedByUser in the schema.
        /// </summary>
        public string CreatedByUser
        {
            get { return _CreatedByUser; }
            set
            {
                OnCreatedByUserChanging(value);
                _CreatedByUser = value;
                OnCreatedByUserChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        public Nullable<DateTime> CreatedDate
        {
            get { return _CreatedDate; }
            set
            {
                OnCreatedDateChanging(value);
                _CreatedDate = value;
                OnCreatedDateChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        public string Title
        {
            get { return _Title; }
            set
            {
                OnTitleChanging(value);
                _Title = value;
                OnTitleChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        public string Description
        {
            get { return _Description; }
            set
            {
                OnDescriptionChanging(value);
                _Description = value;
                OnDescriptionChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        public string Url
        {
            get { return _Url; }
            set
            {
                OnUrlChanging(value);
                _Url = value;
                OnUrlChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property MobileUrl in the schema.
        /// </summary>
        public string MobileUrl
        {
            get { return _MobileUrl; }
            set
            {
                OnMobileUrlChanging(value);
                _MobileUrl = value;
                OnMobileUrlChanged();
            }
        }

        /// <summary>
        /// There are no comments for Property ViewOrder in the schema.
        /// </summary>
        public Nullable<int> ViewOrder
        {
            get { return _ViewOrder; }
            set
            {
                OnViewOrderChanging(value);
                _ViewOrder = value;
                OnViewOrderChanged();
            }
        }

        /// <summary>
        /// Create a new PortalLink object.
        /// </summary>
        /// <param name="moduleId">Initial value of ModuleId.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        public static PortalLink CreatePortalLink(int moduleId, int itemId)
        {
            var portalLink = new PortalLink();
            portalLink.ModuleId = moduleId;
            portalLink.ItemId = itemId;
            return portalLink;
        }

        partial void OnModuleIdChanging(int value);
        partial void OnModuleIdChanged();

        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();

        partial void OnCreatedByUserChanging(string value);
        partial void OnCreatedByUserChanged();

        partial void OnCreatedDateChanging(Nullable<DateTime> value);
        partial void OnCreatedDateChanged();

        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();

        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();

        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();

        partial void OnMobileUrlChanging(string value);
        partial void OnMobileUrlChanged();

        partial void OnViewOrderChanging(Nullable<int> value);
        partial void OnViewOrderChanged();
    }
}