//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Bakopanos")]
[assembly: AssemblyDescription("Bakopanos")]
[assembly: AssemblyCompany("http://code.google.com/p/bakopanos/")]
[assembly: AssemblyProduct("Bakopanos")]
[assembly: AssemblyCopyright("Copyright K. Bakopanos 2008")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("d038566a-1937-478a-b5c5-b79c4afb253d")]
[assembly: AssemblyVersion("1.0.0.73")]
[assembly: AssemblyFileVersion("1.0.0.73")]


